// Spanish/Venezuelan nickname (hipocorístico) and diminutive resolution.
// A family abroad may report "Pepe" while a shelter logs "José" — the engine
// must treat them as the same given name. Maps a nickname to its canonical
// form(s); used to expand name tokens before comparison.

const NICKNAME_TO_CANONICAL: Record<string, string[]> = {
  pepe: ["jose"],
  pepito: ["jose"],
  che: ["jose"],
  cheo: ["jose"],
  chucho: ["jesus"],
  chuy: ["jesus"],
  chus: ["jesus"],
  toni: ["antonio"],
  tono: ["antonio"],
  nono: ["antonio"],
  nacho: ["ignacio"],
  lucho: ["luis"],
  guicho: ["luis"],
  pancho: ["francisco"],
  paco: ["francisco"],
  curro: ["francisco"],
  memo: ["guillermo"],
  guille: ["guillermo"],
  beto: ["alberto", "roberto", "norberto"],
  tito: ["alberto", "ernesto"],
  rober: ["roberto"],
  quico: ["federico", "francisco"],
  kike: ["enrique", "federico"],
  quique: ["enrique"],
  richi: ["ricardo"],
  ricky: ["ricardo"],
  charli: ["carlos"],
  carlitos: ["carlos"],
  cha: ["rosario"],
  mari: ["maria"],
  maru: ["maria"],
  maite: ["maria"],
  marichu: ["maria"],
  conchita: ["concepcion"],
  concha: ["concepcion"],
  lola: ["dolores"],
  loli: ["dolores"],
  lupe: ["guadalupe"],
  pili: ["pilar"],
  rosa: ["rosario"],
  charo: ["rosario"],
  meche: ["mercedes"],
  cuca: ["refugio"],
  nena: ["elena"],
  nona: ["leonor"],
  fina: ["josefina"],
  pina: ["josefina"],
  tere: ["teresa"],
  trini: ["trinidad"],
  cande: ["candelaria"],
  ale: ["alejandro", "alejandra"],
  sandro: ["alejandro"],
  santi: ["santiago"],
  yago: ["santiago"],
  nando: ["fernando", "hernando"],
  fer: ["fernando", "fernanda"],
  rafa: ["rafael"],
  manolo: ["manuel"],
  manu: ["manuel", "manuela"],
  lolo: ["manuel"],
  lalo: ["eduardo", "gonzalo"],
  edu: ["eduardo"],
  gabo: ["gabriel"],
  gabi: ["gabriela", "gabriel"],
  vicky: ["victoria"],
  vico: ["victor"],
  dani: ["daniel", "daniela"],
  cris: ["cristina", "cristian"],
  tina: ["cristina", "agustina"],
  juancho: ["juan"],
  juanca: ["juan"],
  juanma: ["juan"],
  monca: ["ramon"],
  moncho: ["ramon"],
  goyo: ["gregorio"],
  yoli: ["yolanda"],
  cuco: ["refugio"],
};

/** Return the canonical given-name forms for a token (the token itself plus
 *  any names it is a known nickname of). Always includes the input token. */
export function expandName(token: string): string[] {
  const canonical = NICKNAME_TO_CANONICAL[token];
  if (!canonical) return [token];
  return [token, ...canonical];
}
