// Bilingual (EN/ES) explainer content for the HOS landing page, written to be
// understood by a curious 12-year-old yet trusted by an adult official. Every
// user-facing string is a {en, es} pair resolved at render time by useLocale().
//
// Generated by the hos-landing-content workflow, then hand-checked for Spanish
// diacritics. Treat this file as the single source of truth for landing copy.

import type { Bi } from "./LocaleProvider";

export type Principle = { title: Bi; text: Bi };
export type ProblemPoint = { label: Bi; text: Bi };
export type Step = { role: Bi; title: Bi; body: Bi; caption: Bi };
export type Module = {
  id: string;
  name: Bi;
  tagline: Bi;
  body: Bi;
  bullets: Bi[];
  forWho: Bi;
};
export type SourceExample = { name: Bi; example: Bi };
export type TimelineEvent = { date: Bi; label: Bi };
export type TrustBadge = { name: Bi; text: Bi };
export type FutureVersion = {
  version: string;
  name: Bi;
  body: Bi;
  bullets: Bi[];
};
export type NavItem = { id: string; label: Bi };
export type Capability = {
  id: string;
  name: Bi;
  tagline: Bi;
  body: Bi;
  bullets: Bi[];
  forWho: Bi;
  whyNow: Bi;
};
export type AcctStep = { title: Bi; text: Bi };
export type RoadmapItem = { state: "now" | "next" | "exploring"; status: Bi; label: Bi };

export const content = {
  meta: {
    productName: {
      en: "HOS Response Kit - Venezuela 2026",
      es: "Kit de Respuesta HOS - Venezuela 2026",
    },
    tagline: {
      en: "Families, helpers, and responders, together as one.",
      es: "Las familias, quienes ayudan y quienes responden, todos como una sola familia.",
    },
  },
  // United-response banner line, shown under the big-idea heading.
  unityLine: {
    en: "HOS brings families, volunteers, shelters, and responders into one connected response, like one big family working together.",
    es: "HOS reúne a las familias, los voluntarios, los refugios y quienes responden en una sola respuesta conectada, como una gran familia que trabaja unida.",
  },
  hero: {
    eyebrow: {
      en: "Family reunification, first",
      es: "Primero, reunir a las familias",
    },
    headline: {
      en: "Find the people you can't reach",
      es: "Encuentra a quien no puedes localizar",
    },
    subhead: {
      en: "When disaster strikes, families can lose contact in minutes. HOS lets you report a missing loved one, then watches for a possible match day and night.",
      es: "Cuando ocurre un desastre, las familias pueden perder el contacto en minutos. Con HOS reportas a tu ser querido y el sistema busca una posible coincidencia de día y de noche.",
    },
    primaryCta: {
      en: "Report someone missing",
      es: "Reportar a alguien desaparecido",
    },
    secondaryCta: { en: "See how it works", es: "Ver cómo funciona" },
    note: {
      en: "No account needed. It only takes a minute.",
      es: "No necesitas cuenta. Solo toma un minuto.",
    },
  },
  problem: {
    title: {
      en: "The truth is split into pieces",
      es: "La verdad está partida en pedazos",
    },
    intro: {
      en: "During a disaster, news about people pours in every minute from many places at once. Each place holds one small piece of the story, and no one can see the whole picture.",
      es: "Durante un desastre, las noticias sobre las personas llegan cada minuto desde muchos lugares a la vez. Cada lugar guarda una pequeña parte de la historia, y nadie puede ver el cuadro completo.",
    },
    points: [
      {
        label: { en: "Government", es: "Gobierno" },
        text: {
          en: "Official bulletins with names and numbers, posted on their own pages.",
          es: "Boletines oficiales con nombres y números, publicados en sus propias páginas.",
        },
      },
      {
        label: { en: "Hospitals", es: "Hospitales" },
        text: {
          en: "Lists of patients, including people brought in without a name.",
          es: "Listas de pacientes, incluso personas que llegan sin nombre.",
        },
      },
      {
        label: { en: "Red Cross", es: "Cruz Roja" },
        text: {
          en: "Rescue and shelter records kept in their own system.",
          es: "Registros de rescate y refugio guardados en su propio sistema.",
        },
      },
      {
        label: { en: "Volunteers", es: "Voluntarios" },
        text: {
          en: "Quick updates typed into group chats on their phones.",
          es: "Avisos rápidos escritos en chats de grupo desde sus teléfonos.",
        },
      },
      {
        label: { en: "Families", es: "Familias" },
        text: {
          en: "Photos and calls for help posted across many social media apps.",
          es: "Fotos y pedidos de ayuda publicados en muchas redes sociales.",
        },
      },
      {
        label: { en: "News", es: "Noticias" },
        text: {
          en: "Reports that describe people and places in plain words, not data.",
          es: "Reportes que describen personas y lugares en palabras, no en datos.",
        },
      },
    ] as ProblemPoint[],
    punchline: {
      en: "Each piece is true, but they never meet, so families wait and the same help gets done twice.",
      es: "Cada pieza es cierta, pero nunca se juntan, así las familias esperan y la misma ayuda se hace dos veces.",
    },
  },
  bigIdea: {
    title: {
      en: "One shared picture for everyone",
      es: "Un mismo cuadro para todos",
    },
    body: {
      en: "HOS is like a giant shared whiteboard for a disaster. Everyone who helps, from a worried family to a volunteer, a shelter, a hospital, or a responder, adds their piece, and the pieces fit together like a puzzle until one clear picture appears and everyone becomes part of one response. AI quietly sorts the flood of messages into that picture, but people still make every decision.",
      es: "HOS es como una enorme pizarra compartida durante un desastre. Cada persona que ayuda, desde una familia preocupada hasta un voluntario, un refugio, un hospital o quienes responden, agrega su pieza, y las piezas encajan como un rompecabezas hasta formar una imagen clara, y todos pasan a ser parte de una sola respuesta. La IA ordena en silencio la avalancha de mensajes para formar esa imagen, pero las personas siguen tomando cada decisión.",
    },
    principles: [
      {
        title: { en: "AI helps people", es: "La IA ayuda a las personas" },
        text: {
          en: "AI suggests a possible match. A trained person always decides if it is real.",
          es: "La IA sugiere una posible coincidencia. Una persona capacitada siempre decide si es real.",
        },
      },
      {
        title: { en: "Every report matters", es: "Cada reporte importa" },
        text: {
          en: "Even one small detail, like a nickname or a street, can complete the puzzle.",
          es: "Hasta un pequeño detalle, como un apodo o una calle, puede completar el rompecabezas.",
        },
      },
      {
        title: { en: "Works without internet", es: "Funciona sin internet" },
        text: {
          en: "It works on a weak signal and saves your report, then sends it once the connection comes back.",
          es: "Funciona con señal débil y guarda tu reporte, luego lo envía cuando vuelve la conexión.",
        },
      },
      {
        title: { en: "Trust is fundamental", es: "La confianza es fundamental" },
        text: {
          en: "Every report shows who saw it, when, where, and how sure they are.",
          es: "Cada reporte muestra quién lo vio, cuándo, dónde y qué tan seguro está.",
        },
      },
    ] as Principle[],
  },
  howItWorks: {
    title: {
      en: "How a family finds someone again",
      es: "Cómo una familia vuelve a encontrar a alguien",
    },
    intro: {
      en: "Three small steps turn a worried message into a possible match the family can check.",
      es: "Tres pasos sencillos convierten un mensaje de angustia en una posible coincidencia que la familia puede revisar.",
    },
    steps: [
      {
        role: { en: "A worried family member", es: "Una familiar preocupada" },
        title: {
          en: 'She taps "I can\'t reach my family"',
          es: 'Ella toca "No puedo localizar a mi familia"',
        },
        body: {
          en: "A mother in Canada opens the app and taps one button. She types a name, a city, a phone, a last address, and how they are related, and adds a photo if she has one. No account and no fuss, just a few calm questions.",
          es: "Una mamá en Canadá abre la app y toca un solo botón. Escribe un nombre, una ciudad, un teléfono, una última dirección y el parentesco, y agrega una foto si la tiene. Sin cuenta y sin trabas, solo unas pocas preguntas tranquilas.",
        },
        caption: {
          en: "Reports a missing loved one",
          es: "Reporta a un ser querido",
        },
      },
      {
        role: { en: "A volunteer in Caracas", es: "Un voluntario en Caracas" },
        title: {
          en: "He photographs and reports a found person",
          es: "Él fotografía y reporta a una persona encontrada",
        },
        body: {
          en: "At a shelter in Caracas, a volunteer meets a man named Carlos. He takes a photo and writes down what he sees: the name, the place, and that the person is alive and safe. The report keeps a record of who saw him, where, and when.",
          es: "En un refugio en Caracas, un voluntario conoce a un hombre llamado Carlos. Toma una foto y anota lo que ve: el nombre, el lugar y que la persona está viva y a salvo. El reporte guarda quién lo vio, dónde y cuándo.",
        },
        caption: {
          en: "Reports a found person",
          es: "Reporta a una persona encontrada",
        },
      },
      {
        role: { en: "The AI, working quietly", es: "La IA, trabajando en silencio" },
        title: {
          en: 'The AI sends "possible match, 94%"',
          es: 'La IA envía "posible coincidencia, 94%"',
        },
        body: {
          en: "The AI compares every found report against every missing report and notices that Carlos looks like the person the mother is searching for. It sends her a gentle message: possible match, 94 percent confidence. This is a candidate to verify, never an automatic confirmation, so a person checks it before anyone celebrates.",
          es: "La IA compara cada reporte de personas encontradas con cada reporte de personas desaparecidas y nota que Carlos se parece a quien busca la mamá. Le envía un mensaje suave: posible coincidencia, 94 por ciento de confianza. Es un candidato por verificar, nunca una confirmación automática, así que una persona lo revisa antes de que alguien celebre.",
        },
        caption: {
          en: "Suggests a match to verify",
          es: "Sugiere una coincidencia por verificar",
        },
      },
    ] as Step[],
  },
  modules: [
    {
      id: "missing",
      name: {
        en: "Missing Persons Registry",
        es: "Registro de Personas Desaparecidas",
      },
      tagline: {
        en: "Where families report a loved one",
        es: "Donde las familias reportan a un ser querido",
      },
      body: {
        en: "This is the heart of everything. A family enters a name, a city, a phone, a last address, and a photo, and the search begins. No account and no fuss, because a worried person should not have to fight a form.",
        es: "Este es el corazón de todo. Una familia ingresa un nombre, una ciudad, un teléfono, una última dirección y una foto, y la búsqueda comienza. Sin cuenta y sin trabas, porque una persona preocupada no debería pelear con un formulario.",
      },
      bullets: [
        { en: "Report in under a minute", es: "Reporta en menos de un minuto" },
        { en: "Add a photo if you have one", es: "Agrega una foto si la tienes" },
        { en: "Works on a weak connection", es: "Funciona con mala conexión" },
      ],
      forWho: {
        en: "Families searching for someone",
        es: "Familias que buscan a alguien",
      },
    },
    {
      id: "found",
      name: {
        en: "Found Persons Registry",
        es: "Registro de Personas Encontradas",
      },
      tagline: {
        en: "Where helpers report who they found",
        es: "Donde quien ayuda reporta a quien encontró",
      },
      body: {
        en: "Hospitals, shelters, firefighters, volunteers, and the Red Cross report each person they meet. A name, a place, a photo, and whether the person is safe become one clear record everyone can see.",
        es: "Hospitales, refugios, bomberos, voluntarios y la Cruz Roja reportan a cada persona que encuentran. Un nombre, un lugar, una foto y si la persona está a salvo se vuelven un registro claro que todos pueden ver.",
      },
      bullets: [
        { en: "Snap a photo, add the place", es: "Toma una foto, agrega el lugar" },
        { en: "Mark the person safe or hurt", es: "Marca si está a salvo o herida" },
        { en: "Every helper can add a report", es: "Cada ayudante puede sumar un reporte" },
      ],
      forWho: {
        en: "Shelters, hospitals, volunteers, Red Cross",
        es: "Refugios, hospitales, voluntarios, Cruz Roja",
      },
    },
    {
      id: "matching",
      name: { en: "AI Matching Engine", es: "Motor de Coincidencias con IA" },
      tagline: {
        en: "Compares every found to every missing",
        es: "Compara cada encontrado con cada desaparecido",
      },
      body: {
        en: "Like puzzle pieces snapping together, the AI compares found reports against missing reports. It weighs name and nickname, age, description, neighborhood, hospital, GPS, photos, time, and relationships, not face matching alone.",
        es: "Como piezas de rompecabezas que encajan, la IA compara los reportes de encontrados con los reportes de desaparecidos. Toma en cuenta el nombre y el apodo, la edad, la descripción, el barrio, el hospital, el GPS, las fotos, la hora y los parentescos, no solo el rostro.",
      },
      bullets: [
        { en: "Looks at many clues at once", es: "Mira muchas pistas a la vez" },
        { en: "Shows a confidence number", es: "Muestra un número de confianza" },
        { en: "Suggests, never decides for you", es: "Sugiere, nunca decide por ti" },
      ],
      forWho: {
        en: "Works for everyone, in the background",
        es: "Sirve a todos, en segundo plano",
      },
    },
    {
      id: "verification",
      name: { en: "Verification", es: "Verificación" },
      tagline: {
        en: "Makes trust something you can measure",
        es: "Hace que la confianza se pueda medir",
      },
      body: {
        en: "A match is always a candidate to check, never a sure thing. Every report carries who verified it, the evidence, the confidence, the time, the place, and the organization, so people can trust what they see.",
        es: "Una coincidencia siempre es un candidato por revisar, nunca algo seguro. Cada reporte lleva quién lo verificó, la evidencia, la confianza, la hora, el lugar y la organización, para que la gente confíe en lo que ve.",
      },
      bullets: [
        { en: "See who confirmed each report", es: "Ve quién confirmó cada reporte" },
        { en: "Evidence and time are attached", es: "La evidencia y la hora van adjuntas" },
        { en: "A person confirms before it is final", es: "Una persona confirma antes de cerrarlo" },
      ],
      forWho: {
        en: "Responders and families verifying matches",
        es: "Equipos y familias que verifican coincidencias",
      },
    },
    {
      id: "communication",
      name: { en: "Communication", es: "Comunicación" },
      tagline: {
        en: "Reaches families wherever they are",
        es: "Llega a las familias donde estén",
      },
      body: {
        en: "When there is news, the family hears it fast. HOS sends automatic messages by SMS, email, WhatsApp, Telegram, and push, so no one waits by a silent phone wondering.",
        es: "Cuando hay novedades, la familia se entera rápido. HOS envía avisos automáticos por SMS, correo, WhatsApp, Telegram y notificaciones, para que nadie espere junto a un teléfono en silencio.",
      },
      bullets: [
        { en: "Choose the channel that reaches you", es: "Elige el canal que mejor te llega" },
        { en: "Get told the moment there is news", es: "Te avisan apenas hay novedades" },
        { en: "Clear words, no false promises", es: "Palabras claras, sin falsas promesas" },
      ],
      forWho: { en: "Families waiting for news", es: "Familias que esperan noticias" },
    },
  ] as Module[],
  aiDay1: {
    title: {
      en: "What the AI does on the first day",
      es: "Lo que hace la IA desde el primer día",
    },
    body: {
      en: "The AI works quietly in the background. It is not a chat box. It reads public posts and reports, then turns messy words into clear, organized facts. That way the home screen can be a map full of dots, where each dot is a person, a shelter, or a need.",
      es: "La IA trabaja en silencio, de fondo. No es un chat. Lee publicaciones y reportes públicos y convierte palabras desordenadas en datos claros y ordenados. Así la pantalla principal puede ser un mapa lleno de puntos, donde cada punto es una persona, un refugio o una necesidad.",
    },
    sources: [
      {
        name: { en: "Facebook", es: "Facebook" },
        example: {
          en: "Found a lost little girl near the plaza. She is safe with us.",
          es: "Encontramos a una niña perdida cerca de la plaza. Está a salvo con nosotros.",
        },
      },
      {
        name: { en: "Telegram", es: "Telegram" },
        example: {
          en: "We found an older woman near Maiquetia. She does not remember her name.",
          es: "Encontramos a una señora mayor cerca de Maiquetía. No recuerda su nombre.",
        },
      },
      {
        name: { en: "Instagram", es: "Instagram" },
        example: {
          en: "Photo: a man being helped at Shelter 17. Does anyone know who he is?",
          es: "Foto: un hombre atendido en el Refugio 17. ¿Alguien sabe quién es?",
        },
      },
      {
        name: { en: "X", es: "X" },
        example: {
          en: "Family looking for Carlos Perez, last seen in Catia.",
          es: "Familia busca a Carlos Pérez, visto por última vez en Catia.",
        },
      },
      {
        name: { en: "News", es: "Noticias" },
        example: {
          en: "Hospital admits an unidentified man after a building collapse.",
          es: "Un hospital ingresa a un hombre sin identificar tras el derrumbe de un edificio.",
        },
      },
      {
        name: { en: "Volunteer reports", es: "Reportes de voluntarios" },
        example: {
          en: "Two children found and taken to the school on 5th Street.",
          es: "Dos niños encontrados y llevados a la escuela de la calle 5.",
        },
      },
      {
        name: { en: "Government bulletins", es: "Boletines del gobierno" },
        example: {
          en: "Shelter opened at the sports center, with 200 spaces available.",
          es: "Refugio abierto en el polideportivo, con 200 cupos disponibles.",
        },
      },
    ] as SourceExample[],
    outputNote: {
      en: "Every message becomes organized data: Person, Place, Time, and Description.",
      es: "Cada mensaje se convierte en datos ordenados: Persona, Lugar, Hora y Descripción.",
    },
  },
  aiTimeline: {
    title: { en: "The AI timeline", es: "La línea de tiempo de la IA" },
    intro: {
      en: "Clues arrive from many places at different times. The AI gathers them into one clear story, so a family can see what happened, step by step.",
      es: "Las pistas llegan de muchos lugares y a distintas horas. La IA las reúne en una sola historia clara, para que una familia pueda ver qué pasó, paso a paso.",
    },
    question: { en: "What happened to Carlos?", es: "¿Qué le pasó a Carlos?" },
    events: [
      {
        date: { en: "Jun 24", es: "24 jun" },
        label: {
          en: "His phone went silent and stopped connecting.",
          es: "Su teléfono se quedó sin señal y dejó de conectarse.",
        },
      },
      {
        date: { en: "Jun 25", es: "25 jun" },
        label: {
          en: "A neighbor reported that his apartment building collapsed.",
          es: "Un vecino reportó que su edificio se derrumbó.",
        },
      },
      {
        date: { en: "Jun 25", es: "25 jun" },
        label: {
          en: "A firefighter reported rescuing a man from the rubble.",
          es: "Un bombero reportó el rescate de un hombre entre los escombros.",
        },
      },
      {
        date: { en: "Jun 26", es: "26 jun" },
        label: {
          en: "A hospital admitted an unidentified man.",
          es: "Un hospital ingresó a un hombre sin identificar.",
        },
      },
      {
        date: { en: "Jun 26", es: "26 jun" },
        label: {
          en: "The AI suggests an 87% chance that this is Carlos.",
          es: "La IA sugiere un 87% de probabilidad de que sea Carlos.",
        },
      },
    ] as TimelineEvent[],
    note: {
      en: "No person could build this timeline by hand from so many sources. And it is only a suggestion: people still check every step before it counts as true.",
      es: "Ninguna persona podría armar esta línea de tiempo a mano con tantas fuentes. Y es solo una sugerencia: las personas verifican cada paso antes de darlo por cierto.",
    },
  },
  objectModel: {
    title: { en: "One object model", es: "Un solo modelo de objetos" },
    body: {
      en: "HOS is not ten separate apps. Everything in the system is one of ten things, and everything else is simply how those things connect to each other.",
      es: "HOS no son diez aplicaciones separadas. Todo en el sistema es una de diez cosas, y lo demás es simplemente cómo esas cosas se conectan entre sí.",
    },
    objects: [
      {
        title: { en: "Person", es: "Persona" },
        text: {
          en: "Anyone who is missing, found, or helping out.",
          es: "Alguien que está perdido, encontrado o ayudando.",
        },
      },
      {
        title: { en: "Organization", es: "Organización" },
        text: {
          en: "A hospital, a shelter, or a relief group.",
          es: "Un hospital, un refugio o un grupo de ayuda.",
        },
      },
      {
        title: { en: "Volunteer", es: "Voluntario" },
        text: {
          en: "A person who offers their time and skills.",
          es: "Una persona que ofrece su tiempo y sus habilidades.",
        },
      },
      {
        title: { en: "Location", es: "Lugar" },
        text: {
          en: "A place on the map, like an address.",
          es: "Un punto en el mapa, como una dirección.",
        },
      },
      {
        title: { en: "Incident", es: "Incidente" },
        text: {
          en: "Something that happened, like a flood.",
          es: "Algo que ocurrió, como una inundación.",
        },
      },
      {
        title: { en: "Resource", es: "Recurso" },
        text: {
          en: "Help that is available, like water or beds.",
          es: "Ayuda disponible, como agua o camas.",
        },
      },
      {
        title: { en: "Need", es: "Necesidad" },
        text: {
          en: "Something that is missing, like food or medicine.",
          es: "Algo que hace falta, como comida o medicina.",
        },
      },
      {
        title: { en: "Asset", es: "Activo" },
        text: {
          en: "A truck, a boat, or a piece of equipment.",
          es: "Un camión, un bote o un equipo.",
        },
      },
      {
        title: { en: "Mission", es: "Misión" },
        text: {
          en: "A task that someone is working to finish.",
          es: "Una tarea que alguien trabaja para cumplir.",
        },
      },
      {
        title: { en: "Communication", es: "Comunicación" },
        text: {
          en: "A message sent between people or groups.",
          es: "Un mensaje enviado entre personas o grupos.",
        },
      },
    ] as Principle[],
    note: {
      en: "The real value is in the connections between these things, and the AI helps people see them. People still make the decisions.",
      es: "El verdadero valor está en las conexiones entre estas cosas, y la IA ayuda a las personas a verlas. Las personas siguen tomando las decisiones.",
    },
  },
  trust: {
    title: { en: "Trust you can measure", es: "Confianza que se puede medir" },
    body: {
      en: "When a family is waiting, a guess is not good enough. So every report in HOS comes with proof of where it came from and how sure we are. That way, trust is something you can see and check, not just hope for.",
      es: "Cuando una familia espera, una suposición no alcanza. Por eso cada reporte en HOS llega con pruebas de su origen y de qué tan seguro es. Así la confianza es algo que puedes ver y revisar, no solo esperar.",
    },
    badges: [
      {
        name: { en: "Evidence", es: "Evidencia" },
        text: {
          en: "The photo, note, or document that backs up what the report says.",
          es: "La foto, nota o documento que respalda lo que dice el reporte.",
        },
      },
      {
        name: { en: "Provenance", es: "Origen" },
        text: {
          en: "Where the report came from, like a shelter, a hospital, or a volunteer.",
          es: "De dónde vino el reporte: un refugio, un hospital o un voluntario.",
        },
      },
      {
        name: { en: "Timestamp", es: "Fecha y hora" },
        text: {
          en: "The exact day and time the report was made, so nothing gets out of order.",
          es: "El día y la hora exactos en que se hizo el reporte, para que nada se desordene.",
        },
      },
      {
        name: { en: "Confidence", es: "Confianza" },
        text: {
          en: "How sure the AI is about a possible match, shown as a number like 94 percent. It is always a match to check, never a final answer.",
          es: "Qué tan segura está la IA de una posible coincidencia, mostrada como un número, por ejemplo 94 por ciento. Siempre es una coincidencia para revisar, nunca una respuesta final.",
        },
      },
      {
        name: { en: "Verification history", es: "Historial de verificación" },
        text: {
          en: "A list of who checked the report and when, so you can follow every step.",
          es: "Una lista de quién revisó el reporte y cuándo, para que puedas seguir cada paso.",
        },
      },
    ] as TrustBadge[],
    aiNote: {
      en: "AI helps by sorting and suggesting. People always make the final decision.",
      es: "La IA ayuda a ordenar y a sugerir. Las personas siempre toman la decisión final.",
    },
  },
  future: {
    title: { en: "Where HOS grows next", es: "Hacia dónde crece HOS" },
    intro: {
      en: "Once families can find each other, HOS grows to help with the other big needs in a disaster.",
      es: "Cuando las familias puedan encontrarse, HOS crece para ayudar con las otras grandes necesidades en un desastre.",
    },
    versions: [
      {
        version: "Version 2",
        name: { en: "Shelter Directory", es: "Directorio de refugios" },
        body: {
          en: "A live list of every shelter and what it has right now. Families and helpers can see space, food, water, and care before they travel.",
          es: "Una lista en vivo de cada refugio y lo que tiene en este momento. Las familias y quienes ayudan pueden ver espacio, comida, agua y atención antes de viajar.",
        },
        bullets: [
          { en: "Open beds and capacity", es: "Camas libres y capacidad" },
          { en: "Food, water, and power", es: "Comida, agua y electricidad" },
          { en: "Doctor, pets, and wheelchair access", es: "Médico, mascotas y acceso para sillas de ruedas" },
        ],
      },
      {
        version: "Version 3",
        name: { en: "Volunteer Operations", es: "Operaciones de voluntarios" },
        body: {
          en: "A way to see who can help, where they are, and what they can do. Each volunteer gets matched to a job that fits their skills, close to where they are.",
          es: "Una forma de ver quién puede ayudar, dónde está y qué sabe hacer. Cada voluntario se conecta con una tarea que va con sus habilidades, cerca de donde se encuentra.",
        },
        bullets: [
          { en: "Skills and training", es: "Habilidades y formación" },
          { en: "Location and availability", es: "Ubicación y disponibilidad" },
          { en: "Equipment and assignments", es: "Equipo y asignaciones" },
        ],
      },
      {
        version: "Version 4",
        name: { en: "Needs Map", es: "Mapa de necesidades" },
        body: {
          en: "A live map that shows what each area needs and what is blocking the way. Help can go where it is needed most, instead of where people only guess.",
          es: "Un mapa en vivo que muestra qué necesita cada zona y qué está bloqueando el paso. La ayuda puede ir a donde más se necesita, en vez de donde solo se supone.",
        },
        bullets: [
          { en: "Food, water, and medicine", es: "Comida, agua y medicina" },
          { en: "Fuel and open hospitals", es: "Combustible y hospitales abiertos" },
          { en: "Blocked roads and collapsed buildings", es: "Caminos cerrados y edificios derrumbados" },
        ],
      },
      {
        version: "Version 5",
        name: { en: "Resource Logistics", es: "Logística de recursos" },
        body: {
          en: "Track every box, truck, and pallet of aid like a package you can follow. You always know what is on the way and when it should arrive.",
          es: "Sigue cada caja, camión y tarima de ayuda como un paquete que puedes rastrear. Siempre sabes qué viene en camino y cuándo debería llegar.",
        },
        bullets: [
          { en: "Track boxes and pallets", es: "Rastrea cajas y tarimas" },
          { en: "Follow trucks in real time", es: "Sigue los camiones en tiempo real" },
          { en: "Know arrival times", es: "Conoce los tiempos de llegada" },
        ],
      },
    ] as FutureVersion[],
  },
  closing: {
    title: {
      en: "One united response, no one left alone",
      es: "Una sola respuesta unida, nadie se queda solo",
    },
    body: {
      en: "HOS is being built one piece at a time, starting by helping families find the people they love, and growing to connect everyone who helps. Families, volunteers, shelters, hospitals, and responders all share one picture they can trust, like one big family working together.",
      es: "HOS se construye paso a paso, empezando por ayudar a las familias a encontrar a quienes aman, y creciendo para conectar a todos los que ayudan. Las familias, los voluntarios, los refugios, los hospitales y quienes responden comparten una sola imagen en la que pueden confiar, como una gran familia que trabaja unida.",
    },
    cta: {
      en: "Open the live map",
      es: "Abre el mapa en vivo",
    },
    reassurance: {
      en: "No family searches alone, and no helper works alone.",
      es: "Ninguna familia busca sola, y nadie que ayuda trabaja solo.",
    },
  },
  nav: [
    { id: "problem", label: { en: "The problem", es: "El problema" } },
    { id: "how", label: { en: "How it works", es: "Cómo funciona" } },
    { id: "modules", label: { en: "The 5 modules", es: "Los 5 módulos" } },
    { id: "response", label: { en: "Coordinate", es: "Coordinar" } },
    { id: "accountability", label: { en: "Aid delivery", es: "Que llegue" } },
    { id: "trust", label: { en: "Trust", es: "Confianza" } },
  ] as NavItem[],
  roadmap: {
    badge: { en: "Actively building", es: "En desarrollo activo" },
    line: {
      en: "We are building HOS step by step. Here is where it stands today.",
      es: "Estamos construyendo HOS paso a paso. Esto es lo que hay hoy.",
    },
    items: [
      {
        state: "now",
        status: { en: "Building now", es: "En desarrollo ahora" },
        label: { en: "Family reunification — the 5 core modules", es: "Reunificación familiar — los 5 módulos base" },
      },
      {
        state: "next",
        status: { en: "Next", es: "Siguiente" },
        label: { en: "Response coordination — shelters, volunteers, needs, logistics", es: "Coordinación de la respuesta — refugios, voluntarios, necesidades, logística" },
      },
      {
        state: "exploring",
        status: { en: "Exploring", es: "Explorando" },
        label: { en: "Aid accountability — making sure help arrives", es: "Rendición de cuentas — que la ayuda llegue" },
      },
    ] as RoadmapItem[],
  },
  footer: {
    note: {
      en: "More than a preview: HOS is operational software we are actively building — and it already helps coordinate the response and reunite families.",
      es: "Más que una vista previa: HOS es software operativo que estamos construyendo activamente — y que ya ayuda a coordinar la respuesta y a reunir a las familias.",
    },
    disclaimer: {
      en: "This page explains where HOS is going. The data shown here is for example only, not real reports.",
      es: "Esta página explica hacia dónde va HOS. Los datos que se muestran aquí son solo de ejemplo, no reportes reales.",
    },
    copyright: {
      en: "Developed by GARNET CS LLC · 2026 · All rights reserved",
      es: "Desarrollado por GARNET CS LLC · 2026 · Derechos reservados",
    },
  },
  response: {
    eyebrow: { en: "What Venezuela needs now", es: "Lo que Venezuela necesita ahora" },
    title: {
      en: "Coordinate the whole response, together",
      es: "Coordinamos toda la respuesta, juntos",
    },
    intro: {
      en: "Once families can find each other, the next urgent need is coordination: shelters, volunteers, needs, and supplies all working as one. Venezuela needs these four now, together, not as a distant plan.",
      es: "Cuando las familias logran reencontrarse, lo siguiente urgente es coordinar: refugios, voluntarios, necesidades y suministros trabajando como uno solo. Venezuela necesita estas cuatro piezas ahora, juntas, no como un plan lejano.",
    },
    urgency: {
      en: "These four work as one, and Venezuela needs them now, not someday.",
      es: "Estas cuatro funcionan como una sola, y Venezuela las necesita ahora, no algún día.",
    },
    capabilities: [
      {
        id: "volunteers",
        name: { en: "Volunteer Operations", es: "Operación de voluntarios" },
        tagline: { en: "The right helper for the right job", es: "La persona indicada para cada tarea" },
        body: {
          en: "See who can help, what they know how to do, where they are, and what gear they bring. HOS suggests a nearby job that fits each volunteer, so willing hands never sit idle. People make the final call.",
          es: "Ves quién puede ayudar, qué sabe hacer, dónde está y qué equipo trae. HOS sugiere una tarea cercana que encaja con cada voluntario, para que las ganas de ayudar nunca queden paradas. La decisión final la toman las personas.",
        },
        bullets: [
          { en: "Skills, location, and availability in one view", es: "Habilidades, ubicación y disponibilidad en un solo lugar" },
          { en: "Suggested a nearby job that fits", es: "Se sugiere una tarea cercana que encaja" },
          { en: "Equipment and vehicles counted in", es: "También cuentan los equipos y vehículos" },
        ],
        forWho: {
          en: "For neighbors who want to help and the teams who need exactly their skills.",
          es: "Para los vecinos que quieren ayudar y los equipos que necesitan justo lo que ellos saben hacer.",
        },
        whyNow: {
          en: "Thousands want to help today; matching them well doubles what gets done.",
          es: "Miles quieren ayudar hoy; organizarlos bien duplica lo que se logra.",
        },
      },
      {
        id: "needs",
        name: { en: "Needs Map", es: "Mapa de necesidades" },
        tagline: { en: "See where help must go", es: "Ver a dónde debe ir la ayuda" },
        body: {
          en: "A live map of what each area needs and what stands in the way. It shows where food, water, medicine, or fuel run short, which hospitals are open, and which roads are blocked.",
          es: "Un mapa en vivo de lo que cada zona necesita y de lo que estorba el paso. Muestra dónde falta comida, agua, medicina o combustible, cuáles hospitales están abiertos y cuáles calles están bloqueadas.",
        },
        bullets: [
          { en: "Food, water, medicine, and fuel by area", es: "Comida, agua, medicina y combustible por zona" },
          { en: "Open hospitals and blocked roads shown", es: "Hospitales abiertos y calles bloqueadas" },
          { en: "Collapsed buildings and dangers flagged", es: "Edificios caídos y peligros señalados" },
        ],
        forWho: {
          en: "For responders deciding where to go first, and families checking their own street.",
          es: "Para quienes deciden a dónde ir primero y para las familias que revisan su propia calle.",
        },
        whyNow: {
          en: "Aid is wasted when no one knows where the real gaps are right now.",
          es: "La ayuda se pierde cuando nadie sabe dónde están las verdaderas necesidades ahora mismo.",
        },
      },
      {
        id: "logistics",
        name: { en: "Resource & Logistics", es: "Recursos y logística" },
        tagline: { en: "Follow every box of aid", es: "Sigue cada caja de ayuda" },
        body: {
          en: "Track every box, truck, and pallet of aid from start to finish, like a package you can follow. You always know what is on the way, where it is, and when it will arrive.",
          es: "Sigue cada caja, camión y paleta de ayuda de principio a fin, como un paquete que puedes rastrear. Siempre sabes qué viene en camino, dónde está y cuándo llega.",
        },
        bullets: [
          { en: "Track each shipment end to end", es: "Rastrea cada envío de principio a fin" },
          { en: "Know what is on the way", es: "Sabes qué viene en camino" },
          { en: "See exactly where it gets stuck", es: "Ves justo dónde se queda detenido" },
        ],
        forWho: {
          en: "For groups sending aid and the communities counting on it to arrive.",
          es: "Para quienes envían ayuda y las comunidades que cuentan con que llegue.",
        },
        whyNow: {
          en: "When you can follow each load, supplies stop disappearing along the way.",
          es: "Cuando puedes seguir cada carga, los suministros dejan de perderse en el camino.",
        },
      },
      {
        id: "shelter",
        name: { en: "Shelter Directory", es: "Directorio de refugios" },
        tagline: { en: "Every shelter, live and clear", es: "Cada refugio, en vivo y claro" },
        body: {
          en: "A live list of every shelter and what it has right now. Before you go, you can see open spots, food, water, power, a doctor, and access for pets or wheelchairs.",
          es: "Una lista en vivo de cada refugio y de lo que tiene ahora mismo. Antes de ir, puedes ver los cupos, la comida, el agua, la luz, si hay médico y el acceso para mascotas o sillas de ruedas.",
        },
        bullets: [
          { en: "Open spots and beds updated live", es: "Cupos y camas disponibles, al instante" },
          { en: "Food, water, power, and a doctor", es: "Comida, agua, luz y médico" },
          { en: "Pets and wheelchair access marked", es: "Acceso para mascotas y sillas de ruedas" },
        ],
        forWho: {
          en: "For families looking for a safe place, and shelters sharing what they can offer.",
          es: "Para las familias que buscan un lugar seguro y para los refugios que comparten lo que pueden ofrecer.",
        },
        whyNow: {
          en: "Shelters fill up fast; families need to know where there is room today.",
          es: "Los refugios se llenan rápido; las familias necesitan saber hoy dónde hay espacio.",
        },
      },
    ] as Capability[],
  },
  accountability: {
    eyebrow: { en: "Make sure help arrives", es: "Que la ayuda sí llegue" },
    title: {
      en: "Aid that reaches the families who need it",
      es: "Que la ayuda llegue a las familias",
    },
    problem: {
      en: "Sometimes aid gets blocked, held up, or sent somewhere else along the way. So the families waiting for food, water, or medicine never receive it.",
      es: "A veces la ayuda se bloquea, se detiene o se desvía en el camino. Por eso, las familias que esperan comida, agua o medicina nunca la reciben.",
    },
    body: {
      en: "With HOS, anyone can report when aid did not arrive, with a photo and a place. Every delivery is tracked from start to finish, so it is clear where the help went and where it got stuck.",
      es: "Con HOS, cualquier persona puede reportar cuando la ayuda no llegó, con una foto y un lugar. Cada entrega se sigue de principio a fin, para que quede claro a dónde fue la ayuda y dónde se quedó detenida.",
    },
    steps: [
      {
        title: { en: "Report what did not arrive", es: "Reporta lo que no llegó" },
        text: {
          en: "If help never reached you, say so. Add a photo and the place, so others can see what is missing and where.",
          es: "Si la ayuda no llegó, dilo. Agrega una foto y el lugar, para que otros vean qué falta y dónde.",
        },
      },
      {
        title: { en: "Track every delivery from start to finish", es: "Sigue cada entrega de principio a fin" },
        text: {
          en: "Each box, truck, and pallet is followed along the way, like a package you can watch. You always know what is coming and where it is.",
          es: "Cada caja, camión y paleta se sigue en el camino, como un paquete que puedes ver. Así siempre sabes qué viene en camino y dónde está.",
        },
      },
      {
        title: { en: "Flag and verify", es: "Marca y verifica" },
        text: {
          en: "Blockages and detours show up on the map for everyone to see. People review each report, so it is checked, not just assumed.",
          es: "Los bloqueos y desvíos aparecen en el mapa para que todos los vean. Las personas revisan cada reporte, así se verifica y no se da por hecho.",
        },
      },
    ] as AcctStep[],
    bullets: [
      { en: "Report aid that did not arrive", es: "Reporta la ayuda que no llegó" },
      { en: "Follow each box and truck", es: "Sigue cada caja y cada camión" },
      { en: "See on the map where help got stuck", es: "Ve en el mapa dónde se quedó detenida la ayuda" },
      { en: "Every report carries evidence and is verified", es: "Cada reporte trae evidencia y se verifica" },
    ] as Bi[],
    note: {
      en: "Reports are based on evidence and checked by people. This is about transparency and helping aid reach families, never about blaming anyone.",
      es: "Los reportes se basan en evidencia y los revisan personas. Se trata de transparencia y de que la ayuda llegue a las familias, nunca de culpar a nadie.",
    },
  },
} as const;

export type LandingContent = typeof content;
